import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Abhishek',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Sofa',
      slug: 'sofa',
      category: 'Sofa',
      image: '/images/p1.jpeg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Abhis',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality sofa',
    },
    {
      // _id: '2',
      name: 'Couch',
      slug: 'couch',
      category: 'Couch',
      image: '/images/p2.jpeg',
      price: 250,
      countInStock: 0,
      brand: 'Hatui',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '3',
      name: 'Chair',
      slug: 'chair',
      category: 'Chair',
      image: '/images/p3.jpeg',
      price: 25,
      countInStock: 15,
      brand: 'hatui',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      // _id: '4',
      name: 'Table',
      slug: 'table',
      category: 'Table',
      image: '/images/p4.jpeg',
      price: 65,
      countInStock: 5,
      brand: 'Abhi',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Table-cum-stool',
      slug: 'table-cum-stool',
      category: 'Table',
      image: '/images/p5.jpeg',
      price: 150,
      countInStock: 10,
      brand: 'Abhi',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Rocking-Chair',
      slug: 'rocking-chair',
      category: 'Chair',
      image: '/images/p6.jpeg',
      price: 650,
      countInStock: 1,
      brand: 'Abhi',
      rating: 2.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Pink-sofa',
      slug: 'pink-sofa',
      category: 'Sofa',
      image: '/images/p7.jpeg',
      price: 670,
      countInStock: 3,
      brand: 'Abhi',
      rating: 5.0,
      numReviews: 100,
      description: 'high quality product',
    },
    {
      name: 'Designer-sofa',
      slug: 'des-sofa',
      category: 'Sofa',
      image: '/images/p8.jpeg',
      price: 65,
      countInStock: 5,
      brand: 'Abhi',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'black-chair',
      slug: 'plastic-chair',
      category: 'Chair',
      image: '/images/p9.jpeg',
      price: 105,
      countInStock: 50,
      brand: 'Abhi',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Vase',
      slug: 'vase',
      category: 'Vase',
      image: '/images/p10.jpeg',
      price: 400,
      countInStock: 10,
      brand: 'Abhi',
      rating: 0.0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
      name: 'Wooden-Table',
      slug: 'small-table',
      category: 'Table',
      image: '/images/p11.jpeg',
      price: 500,
      countInStock: 34,
      brand: 'Abhi',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Kids-chair',
      slug: 'kids-chair',
      category: 'Chair',
      image: '/images/p12.jpeg',
      price: 1000,
      countInStock: 3,
      brand: 'Abhi',
      rating: 2.5,
      numReviews: 10,
      description: 'high quality product',
    },
    
  ],
};
export default data;
